### ISSUE TITLE
2020-nCoV is not a thing

### ISSUE THREAD

**Issue by Kreyren** [kgostic/traveller_screening#3]
Based on https://en.wikipedia.org/wiki/2019_novel_coronavirus_(2019-nCoV) and provided references this virus is identified as `Novel Coronavirus (2019-nCoV)` unless you have a valid proof of it mutating to require a new identification.

![image](https://user-images.githubusercontent.com/11302521/73601116-bc32ae80-455b-11ea-82e8-662dac0ee612.png)

EDIT: Your own material even identifies it as 2019-nCoV
![image](https://user-images.githubusercontent.com/11302521/73601188-fd778e00-455c-11ea-939b-d1b0d06fa823.png)

**Comment by acrgomez** [comment]
we are very aware that the current name of the pathogen is 2019-nCoV. The
file name is in reference to the year when the work was done.

**Comment by Kreyren** [comment]
> The file name is in reference to the year when the work was done.

With all due respect i don't see why would that make a sense and i believe that it only creates a confusion since the virus is the same as it was before there are no mutations or anything different that would require a new identification and you have the date to when the research was conducted on the paper itself.

**Comment by acrgomez** [comment]
2019-nCoV is not even the permanent name of the pathogen. We did not
consider that the name of our file would have any importance, and the
developer is used to putting the year when the work was done in the file
name. But thanks for your input, we will consider changing it.

**Comment by Kreyren** [comment]
closing as acknowledged
